# Generated by Django 3.2.13 on 2022-06-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineIn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
