# Generated by Django 3.0.3 on 2022-08-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineIn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='user',
            new_name='occupied_by',
        ),
    ]
