# Generated by Django 3.2.13 on 2022-06-11 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dineIn', '0002_auto_20220611_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=5)),
                ('status', models.BooleanField(default=False)),
                ('totalPrice', models.IntegerField(default=0)),
                ('order_payment_amount', models.IntegerField(default=0)),
                ('order_payment_status', models.CharField(max_length=50)),
                ('order_payment_id', models.CharField(max_length=50)),
                ('order_time', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(verbose_name='date published')),
                ('order_status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dineIn.foodmenu')),
            ],
        ),
    ]
