# Generated by Django 3.0.3 on 2022-08-17 18:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dineIn', '0003_auto_20220817_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='occupied_by',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
