# Generated by Django 3.2.13 on 2022-06-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineIn', '0003_foodmenu_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order_no',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
