# Generated by Django 3.2.13 on 2022-06-12 01:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dineIn', '0004_table_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='table',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tableNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='table',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dineIn.foodmenu'),
        ),
    ]
