# Generated by Django 3.0.3 on 2022-08-17 18:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dineIn', '0004_auto_20220817_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='occupied_by',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
